[package]
name = "testfoo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
name = "embed"
crate-type = ["dylib"]
